version: '3'
services:
  postgres:
    image: postgres:11
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./modules/service/src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
      - ./test-cert/server.crt:/var/lib/postgresql/server.crt
      - ./test-cert/server.key:/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:     jimmy
      POSTGRES_PASSWORD: banana
      POSTGRES_DB:       lucuma-sso
  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
