name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache SBT
        uses: coursier/cache-action@v6
      - name: Set up cert permissions (1)
        run: chmod 600 test-cert/server.key
      - name: Set up cert permissions (2)
        run: sudo chown 999 test-cert/server.key
      - name: Start up Postgres instances
        run: docker-compose up -d
      - name: Compile and test
        run: sbt headerCheck clean coverage "set frontendClient.js/coverageEnabled := false" test coverageReport coverageAggregate
      - name: Shut down Postgres instances
        run: docker-compose down
      - name: Upload code coverage data
        run: bash <(curl -s https://codecov.io/bash)
